### ISSUE TITLE
Dynamic Binding is not working

### ISSUE THREAD

**Issue by abhishek-ui** [farengeyt451/ngx-tippy-wrapper#1]
Hi @farengeyt451 ,

Thanks for building this component.

I was trying to bind dynamic tool-tip content. But its not working.
Is there is any way to fix.
ex.component.ts
`toolTipContent: string = "Lorem Ipsum";`

ex.component.html
```
<span ngxTippy [data-tippy-content]="toolTipContent">
  Tippy
</span>
```

I tried using Element too but there too did not get any luck.

ex.component.html
```
<div>

  <span ngxTippy [tippyProps]="tippyContent">
     Tippy with HTML content
  </span>

  <div #tippyTemplate style="display: none;">
    <span>{{toolTipContent}}</span>
   </div>

</div>
```

ex.component.ts
```
import { NgxTippyProps } from 'ngx-tippy-wrapper';
 
@Component({...})

export class ExComponent implements OnInit {
  toolTipContent: string = Lorem Ipsum;
  @ViewChild('tippyTemplate', { static: true }) tippyTemplate: ElementRef;
 
  tippyContent: NgxTippyProps = {
    trigger: 'click',
    allowHTML: true
  };
 
  ngOnInit() {
    this.tippyContent.content = this.tippyTemplate.nativeElement.innerHTML;
  }
}
```

Please help me if there is any way to get dynamic binding data in tooltip.

**Comment by farengeyt451** [comment]
Hi @abhishek-ui . I create small [demo](https://codesandbox.io/s/jolly-engelbart-s8q4n?file=/src/app/app.component.html) with basic content binding. Since it wrapper for native js plugin - we can not use dynamic binding in the usual style, instead we can set initial content and then, if need, append new content using `setTippyContent()` method. Hope it helps you )
I am working on update, this is not finished yet, but you can read content binding approaches docs [here](https://github.com/farengeyt451/ngx-tippy-wrapper/tree/tippy-wrapper2.0#applying-content). Full demo in plans)
